#!/usr/bin/env php
<?php
declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use LegoCue\Framework\Application;
use Monoposer\Commands\Console;

$app = new Application();

$app->loadCommands( new Console() );
$app->terminate();
